language: java

script: ./gradlew build

deploy:
  provider: releases
  api_key: d5d8d4ae506dab455690a584e1ef4492e328e93b 
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/**/*
  skip_cleanup: true
  on:
    tags: true
